### ISSUE TITLE
Single Electron app supporting multiple languges with Angular i18n

### ISSUE THREAD

**Issue by wartab** [dashkan/ng-electron-devkit#2]
Hello there,

I have been looking around for a proper system to develop Angular apps for the browser and Electron at once. This package seems to be the cleanest approach, but I was wondering if there is an "easy" way to include all languages defined in our Angular application within the final electron build.

As I see it currently, it seems like I'd need to generate one build per language.

The use case would be to retrieve the locale (https://github.com/sindresorhus/os-locale) of the user running Electron in order to determine which transalted app to load.

Angular itself is also limited in a similar way forcing you to generate one build per language.

**Comment by dashkan** [comment]
@wartab ,

Just keep in mind that this package currently does not target electron main process. Your application needs to handle localization for the electron main process. 

I do want to want to add main process build and angular schematics by the end of the year.

I don't have much experience w/ internationalization. I would post to StackOverflow to get better advice or alternatives to Angular i8n.
