### ISSUE TITLE
ng serve

### ISSUE THREAD

**Issue by dottodot** [dashkan/ng-electron-devkit#3]
Just wondering is there a way to use this along with ng serve i.e ao you can live build in electron?

**Comment by dashkan** [comment]
You need to pass --serve to your main electron process. Take a look at the provided [sample](/dashkan/ng-electron-devkit/tree/master/sample) application. 

You also need to update your angular.json to support serving to electron. Take a look at the [sample angular.json](/dashkan/ng-electron-devkit/blob/master/sample/angular.json#L161).

Keep in mind that when you serve you have to use the angular dev server, not the local file system.

I'll try to update the documentation over the weekend.
